# SPDX-FileCopyrightText: 2023, 2024 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 MASH project contributors
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure ntfy paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ ntfy_uid }}"
    group: "{{ ntfy_gid }}"
  with_items:
    - "{{ ntfy_base_path }}"
    - "{{ ntfy_config_path }}"
    - "{{ ntfy_data_path }}"
    - "{{ ntfy_cache_path }}"
    - "{{ ntfy_attachment_cache_path }}"

- name: Ensure ntfy support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ ntfy_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ ntfy_uid }}"
    group: "{{ ntfy_gid }}"
  with_items:
    - env
    - labels

- name: Ensure ntfy configuration file installed
  ansible.builtin.copy:
    content: "{{ ntfy_configuration | to_nice_yaml(indent=2, width=999999) }}"
    dest: "{{ ntfy_config_path }}/server.yml"
    mode: "0644"
    owner: "{{ ntfy_uid }}"
    group: "{{ ntfy_gid }}"

- name: Ensure ntfy container image is pulled via community.docker.docker_image
  when: sysd_docker_image_pull_method == 'ansible-module'
  community.docker.docker_image:
    name: "{{ ntfy_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ ntfy_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else ntfy_container_image_force_pull }}"
  register: result
  retries: "{{ container_retry }}"
  delay: "{{ container_retry_delay }}"
  until: result is not failed

- name: Ensure ntfy container image is pulled via ansible.builtin.command
  when: sysd_docker_image_pull_method == 'command'
  ansible.builtin.command:
    cmd: "{{ sysd_docker_host_command }} pull {{ ntfy_container_image }}"
  register: result
  retries: "{{ container_retry }}"
  delay: "{{ container_retry_delay }}"
  until: result is not failed
  changed_when: "'Downloaded newer image' in result.stdout"

- name: Ensure ntfy container network is created via community.docker.docker_network
  when: sysd_docker_net_creation_method == 'ansible-module'
  community.docker.docker_network:
    enable_ipv6: "{{ sysd_docker_ipv6_enabled }}"
    name: "{{ ntfy_container_network }}"
    driver: bridge
    driver_options: "{{ sysd_docker_net_driver_opts }}"

- name: Ensure ntfy container network is created via ansible.builtin.command
  when: sysd_docker_net_creation_method == 'command'
  ansible.builtin.command:
    cmd: >-
      {{ sysd_docker_host_command }} network create
      {% if sysd_docker_ipv6_enabled %}--ipv6{% endif %}
      {{ sysd_docker_net_driver_opts_string }}
      {{ ntfy_container_network }}
  register: network_creation_result
  changed_when: network_creation_result.rc == 0
  failed_when: network_creation_result.rc != 0 and 'already exists' not in network_creation_result.stderr

- name: Ensure ntfy systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/ntfy.service.j2"
    dest: "{{ sysd_docker_service_path }}/{{ ntfy_identifier }}.service"
    mode: "0644"
